module Binds exposing (..)

import Dict exposing (Dict)
import Common exposing (..)

defaultBinds : Dict TF2Key String
defaultBinds = Dict.fromList
    -- https://wiki.teamfortress.com/w/images/c/c8/Config_default.cfg.txt
    [ ("`",           "toggleconsole")
    , ("w",           "+forward")
    , ("s",           "+back")
    , ("a",           "+moveleft")
    , ("d",           "+moveright")
    , ("SPACE",       "+jump")
    , ("CTRL",        "+duck")
    , ("TAB",         "+showscores")
    , ("'",           "+moveup")
    , ("/",           "+movedown")
    , ("PGUP",        "+lookup")
    , ("PGDN",        "+lookdown")
    , ("END",         "centerview")
    , ("ALT",         "+strafe")
    , ("INS",         "+klook")
    -- , ("SEMICOLON",   "+mlook") -- commented in source
    , ("r",           "+reload")
    , ("MOUSE1",      "+attack")
    , ("MOUSE2",      "+attack2")
    , ("MOUSE3",      "+attack3")
    -- , ("z",           "saveme") -- comment in source
    , ("z",           "voice_menu_1")
    , ("x",           "voice_menu_2")
    , ("c",           "voice_menu_3")
    , ("e",           "dropitem")
    , ("1",           "slot1")
    , ("2",           "slot2")
    , ("3",           "slot3")
    , ("4",           "slot4")
    , ("5",           "slot5")
    , ("6",           "slot6")
    , ("7",           "slot7")
    , ("8",           "slot8")
    , ("9",           "slot9")
    , ("0",           "slot10")
    , ("MWHEELUP",    "invprev")
    , ("MWHEELDOWN",  "invnext")
    , ("q",           "lastinv")
    , ("F5",          "screenshot")
    , ("F6",          "save_replay")
    , ("F7",          "abuse_report_queue")
    , ("F10",         "quit prompt")
    , ("F12",         "replay_togglereplaytips")
    , ("PAUSE",       "pause")
    , ("ESCAPE",      "escape")
    , ("t",           "impulse 201")
    , ("y",           "say")
    , ("u",           "say_team")
    , ("v",           "+voicerecord")
    , (".",           "changeteam")
    , (",",           "changeclass")
    , ("F1",          "+showroundinfo")
    , ("g",           "+taunt")
    , ("h",           "+use_action_slot_item")
    , ("e",           "voicemenu 0 0")
    , ("b",           "lastdisguise")
    , ("l",           "dropitem")
    , ("i",           "showmapinfo")
    , ("-",           "disguiseteam")
    , ("m",           "open_charinfo_direct")
    , ("n",           "open_charinfo_backpack")
    , ("f",           "inspect")
    , ("j",           "cl_trigger_first_notification")
    ]


